### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  neighbor: 192.168.0.55 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /bev_time_ref # send the messages of this ROS topic
  msg_type: std_msgs/Header # ROS message type (rosmsg style)
  max_freq: 1000 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3001 # ports of send_topics should be different

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /veh_2/bev # the received messages will be published in this topic
  msg_type: detection_msgs/BevFeature # ROS message type (rosmsg style)
  srcIP: neighbor # message source IPname 
  srcPort: 3001 # message source port 
