### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robot1: 192.168.3.13
  test_local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /tracking2/transformed_objects_box_score_label # the received messages will be published in this topic
  msg_type: visualization_msgs/MarkerArray # ROS message type (rosmsg style)
  srcIP: self # message source IPname
  max_freq: 10 # max sending frequency (Hz) int
  srcPort: 3001 # message source port
- topic_name: /os_header # send the messages of this ROS topic
  msg_type: std_msgs/Header # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self # message source IPname
  srcPort: 3002 # ports of send_topics should be different
- topic_name: /tracking2/transformed_objects_header_box_score_label # the received messages will be published in this topic
  msg_type: visualization_header_msgs/MarkerArrayHeader # ROS message type (rosmsg style)
  srcIP: self # self IP 
  max_freq: 10 # max sending frequency (Hz) int
  srcPort: 3003 # message source port
- topic_name: /tracking2/transformed_det_box_score_label # the received messages will be published in this topic
  msg_type: visualization_msgs/MarkerArray # ROS message type (rosmsg style)
  srcIP: self # self IP 
  max_freq: 10 # max sending frequency (Hz) int
  srcPort: 3004 # message source port

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /tracking/transformed_objects_box_score_label # send the messages of this ROS topic
  msg_type: visualization_msgs/MarkerArray # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: robot1 # self IP
  srcPort: 3001 # ports of send_topics should be different
- topic_name: /rs_header # send the messages of this ROS topic
  msg_type: std_msgs/Header # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: robot1 # self IP
  srcPort: 3002 # ports of send_topics should be different
- topic_name: /tracking/transformed_objects_header_box_score_label # the received messages will be published in this topic
  msg_type: visualization_header_msgs/MarkerArrayHeader # ROS message type (rosmsg style)
  srcIP: robot1 # self IP 
  max_freq: 10 # max sending frequency (Hz) int
  srcPort: 3003 # message source port
- topic_name: /tracking/transformed_det_box_score_label # the received messages will be published in this topic
  msg_type: visualization_msgs/MarkerArray # ROS message type (rosmsg style)
  srcIP: robot1 # self IP 
  max_freq: 10 # max sending frequency (Hz) int
  srcPort: 3004 # message source port
