### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: '*'   # '*' stands for all self IPs
  robot2: 192.168.1.143
  test_local: 127.0.0.1 # just for local machine test

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
send_topics:
- topic_name: /tracking/objects_fusion_box_score # send the messages of this ROS topic
  msg_type: visualization_msgs/MarkerArray # ROS message type (rosmsg style)
  max_freq: 10 # max sending frequency (Hz) int
  srcIP: self # self IP
  srcPort: 3001 # ports of send_topics should be different

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
- topic_name: /rslidar_laserscan # the received messages will be published in this topic
  msg_type: sensor_msgs/LaserScan # ROS message type (rosmsg style)
  srcIP: robot2 # message source IPname
  srcPort: 3001 # message source port